{
    "with_http_error": {
        "output_message": "The server couldn't fulfill the request.\nError code: {code}",
        "string_with_exception_creation": "HTTPError(None, code, None, None, None)",
        "exception_attributes": {
            "code": 404
        }
    },
    "with_url_error": {
        "output_message": "Failed to reach a server.\nReason: {reason}",
        "string_with_exception_creation": "URLError(reason)",
        "exception_attributes": {
            "reason": "[Errno 11001] getaddrinfo failed"
        }
    },
    "with_value_error": {
        "output_message": "Generic exception: {error_message}",
        "string_with_exception_creation": "ValueError(error_message)",
        "exception_attributes": {
            "error_message": "unknown url type: ''"
        }
    }
}
